name: Scan Server
slug: scan-server
description: Use your Home Assistant system as a scan server.

version: "05.08.26_112"

startup: services
boot: auto

arch:
  - aarch64
  - amd64

init: false
host_network: true
usb: true

hassio_api: true
homeassistant_api: true
hassio_role: manager

map:
  - addon_config:rw
  - homeassistant_config:rw
  - share:rw

options:
  filename_base: scanserver
  netshare_server: ""
  netshare_username: ""
  netshare_password: ""
  netshare_path: ""

schema:
  filename_base: str
  netshare_server: str?
  netshare_username: str?
  netshare_password: password?
  netshare_path: str?
